/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfaz;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.stream.Collectors;
import javax.swing.Box;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import poo.javacorp.Productos;
import poo.javacorp.Usuarios;

/**
 *
 * @author s3rzh
 */
public class SubVentasProd extends javax.swing.JInternalFrame {
	public boolean activo;
	public String PATH = "src/main/java/ficheros/ventass.dat";
	public HashMap<LocalDateTime, HashMap<Usuarios, ArrayList<Productos>>> todasVentas = new HashMap<>();
	
	public SubVentasProd() {
		initComponents();
		activo = true;
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                panelVentas = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                diaL = new javax.swing.JTextField();
                mesL = new javax.swing.JTextField();
                anoL = new javax.swing.JTextField();
                buscarB = new javax.swing.JButton();
                errorM = new javax.swing.JLabel();

                setBorder(null);
                setClosable(true);
                addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
                        public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                        }
                        public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                        }
                        public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                                formInternalFrameClosing(evt);
                        }
                        public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
                        }
                        public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
                        }
                        public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
                        }
                        public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                        }
                });

                jScrollPane1.setBorder(null);

                panelVentas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ventas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Source Han Sans KR Heavy", 2, 14), new java.awt.Color(0, 0, 0))); // NOI18N
                panelVentas.setLayout(new javax.swing.BoxLayout(panelVentas, javax.swing.BoxLayout.Y_AXIS));
                jScrollPane1.setViewportView(panelVentas);

                jLabel1.setText("Dia");

                jLabel2.setText("Mes");

                jLabel3.setText("Año");

                diaL.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyTyped(java.awt.event.KeyEvent evt) {
                                diaLKeyTyped(evt);
                        }
                });

                mesL.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyTyped(java.awt.event.KeyEvent evt) {
                                mesLKeyTyped(evt);
                        }
                });

                anoL.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyTyped(java.awt.event.KeyEvent evt) {
                                anoLKeyTyped(evt);
                        }
                });

                buscarB.setText("Buscar");
                buscarB.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                buscarBActionPerformed(evt);
                        }
                });

                errorM.setFont(new java.awt.Font("Source Han Sans KR Heavy", 2, 12)); // NOI18N

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3))
                                                .addGap(29, 29, 29))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(anoL, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mesL, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(diaL, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(39, 39, 39)
                                                .addComponent(errorM, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(171, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(buscarB, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(132, 132, 132))))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(diaL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(mesL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(21, 21, 21)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(anoL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(buscarB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(errorM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(34, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
                // TODO add your handling code here:
		this.dispose();
		activo = false;
        }//GEN-LAST:event_formInternalFrameClosing

        private void diaLKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diaLKeyTyped

		if(diaL.getText().length() >= 2){
			evt.consume();	
		}
		char c = evt.getKeyChar();
		if(c<'0' || c>'9'){
			evt.consume();
		}
        }//GEN-LAST:event_diaLKeyTyped

        private void mesLKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mesLKeyTyped
                // TODO add your handling code here:
		if(mesL.getText().length() >= 2){
			evt.consume();	
		}
		char c = evt.getKeyChar();
		if(c<'0' || c>'9'){
			evt.consume();
		}
        }//GEN-LAST:event_mesLKeyTyped

        private void anoLKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anoLKeyTyped
                // TODO add your handling code here:
		char c = evt.getKeyChar();
		if(anoL.getText().length() >= 4){
			evt.consume();	
		}
		if(c<'0' || c>'9'){
			evt.consume();
		}
        }//GEN-LAST:event_anoLKeyTyped

	public boolean camposVacios(){
		boolean estaVacioOerror;
		
		if (diaL.getText().equals("") || mesL.getText().equals("") || anoL.getText().equals("")) {
			estaVacioOerror = true;
		}else{
			int dia = Integer.parseInt(diaL.getText());
			int mes = Integer.parseInt(mesL.getText());
			int ano = Integer.parseInt(anoL.getText());
			estaVacioOerror = !(dia > 0 && dia <= 29 && mes > 0 && mes <= 12 && ano >= 2000 && ano <= 2022);
		}
		
		return estaVacioOerror;
	}
	
	public void buscarVentas(){
		File archivo = new File(PATH);
		if(archivo.exists() && archivo.isFile()){
			
			FileInputStream tmp = null;
			try {
				tmp = new FileInputStream(PATH);
				ObjectInputStream aa = new ObjectInputStream(tmp);
				todasVentas = (HashMap<LocalDateTime, HashMap<Usuarios, ArrayList<Productos>>>)aa.readObject();
				tmp.close();
				aa.close();
			} catch (FileNotFoundException ex) {
				System.out.println(ex);
			} catch (IOException | ClassNotFoundException ex) {
				System.out.println(ex);
			}
			mostrarVentas();
			errorM.setText("");
		}else{
			errorM.setText("No hay ninguna venta, lo siento.");
		}
	}
	
	public void mostrarVentas(){
		System.out.println(todasVentas);
		for (Map.Entry<LocalDateTime, HashMap<Usuarios, ArrayList<Productos>>> entry : todasVentas.entrySet()) {
			LocalDateTime fecha = entry.getKey();
			JLabel fec = new JLabel("Fecha de compra: " + fecha);
			panelVentas.add(fec);
			panelVentas.add(Box.createRigidArea(new Dimension(0, 7)));
			for (Map.Entry<Usuarios, ArrayList<Productos>> entry1 : entry.getValue().entrySet()) {
				Usuarios usu = entry1.getKey();
				ArrayList<Productos> prod = entry1.getValue();
				JLabel usuNombre = new JLabel(usu.getNombre() + " ");
				usuNombre.setFont(new Font("Source Han Sans KR Heavy", Font.ITALIC, 14));
				panelVentas.add(usuNombre);
				panelVentas.add(Box.createRigidArea(new Dimension(0, 7)));
				for (Productos product : prod) {
					ImageIcon i = new ImageIcon(product.getFotografia());
					Image aux = i.getImage().getScaledInstance(60, 60, java.awt.Image.SCALE_SMOOTH);
					i = new ImageIcon(aux);
					JLabel test = new JLabel(product.getCaracteristicas(),i, SwingConstants.RIGHT);
					JLabel cant = new JLabel("Cantidad: "+product.getStockCantidad());
					JLabel precio = new JLabel("Precio: "+product.getPrecio() + "€");
					panelVentas.add(test);
					panelVentas.add(cant);
					panelVentas.add(precio);
					panelVentas.add(Box.createRigidArea(new Dimension(0, 10)));
					pack();
				}
			}
			panelVentas.add(Box.createRigidArea(new Dimension(0, 20)));
		}
	}
	
        private void buscarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBActionPerformed
                // TODO add your handling code here:

		panelVentas.removeAll();
		pack();
		
		if(diaL.getText().equals("") && mesL.getText().equals("") && anoL.getText().equals("")){
			buscarVentas();
		}else{
		
			if(!camposVacios()){
				errorM.setText("");
				buscarVentas();

			}else{
				errorM.setText("¡Hay campos sin rellenar o están fuera de rango!");
				errorM.setForeground(Color.red);
			}
		}
        }//GEN-LAST:event_buscarBActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTextField anoL;
        private javax.swing.JButton buscarB;
        private javax.swing.JTextField diaL;
        private javax.swing.JLabel errorM;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextField mesL;
        private javax.swing.JPanel panelVentas;
        // End of variables declaration//GEN-END:variables
}
