/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import poo.javacorp.Usuarios;

/**
 *
 * @author s3rzh
 */
public class VistaAdmin extends javax.swing.JFrame {

	private SubAltaProducto alta;
	private SubUsuarios usua;
	private SubBajaProducto baja;
	private SubModProducto modifica;
	private SubVentasProd ventas;
	private Usuarios usuario;
	
	
	public VistaAdmin(Usuarios usuario) {
		initComponents();
		this.usuario = usuario;
		this.setExtendedState(MAXIMIZED_BOTH);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                deskPanel = new javax.swing.JDesktopPane();
                jMenuBar1 = new javax.swing.JMenuBar();
                subVentas = new javax.swing.JMenu();
                jMenuItem1 = new javax.swing.JMenuItem();
                jMenu2 = new javax.swing.JMenu();
                subDarAlta = new javax.swing.JMenuItem();
                subDarBaja = new javax.swing.JMenuItem();
                subModificar = new javax.swing.JMenuItem();
                menuUsuarios = new javax.swing.JMenu();
                todosUsuarios = new javax.swing.JMenuItem();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setBackground(new java.awt.Color(0, 204, 204));

                javax.swing.GroupLayout deskPanelLayout = new javax.swing.GroupLayout(deskPanel);
                deskPanel.setLayout(deskPanelLayout);
                deskPanelLayout.setHorizontalGroup(
                        deskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 908, Short.MAX_VALUE)
                );
                deskPanelLayout.setVerticalGroup(
                        deskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 489, Short.MAX_VALUE)
                );

                subVentas.setMnemonic('R');
                subVentas.setText("Reportes");

                jMenuItem1.setText("Ventas");
                jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jMenuItem1ActionPerformed(evt);
                        }
                });
                subVentas.add(jMenuItem1);

                jMenuBar1.add(subVentas);

                jMenu2.setMnemonic('P');
                jMenu2.setText("Productos");

                subDarAlta.setText("Dar alta");
                subDarAlta.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                subDarAltaActionPerformed(evt);
                        }
                });
                jMenu2.add(subDarAlta);

                subDarBaja.setText("Dar baja");
                subDarBaja.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                subDarBajaActionPerformed(evt);
                        }
                });
                jMenu2.add(subDarBaja);

                subModificar.setText("Modificar");
                subModificar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                subModificarActionPerformed(evt);
                        }
                });
                jMenu2.add(subModificar);

                jMenuBar1.add(jMenu2);

                menuUsuarios.setMnemonic('U');
                menuUsuarios.setText("Usuarios");

                todosUsuarios.setText("Todos los usuarios");
                todosUsuarios.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                todosUsuariosActionPerformed(evt);
                        }
                });
                menuUsuarios.add(todosUsuarios);

                jMenuBar1.add(menuUsuarios);

                setJMenuBar(jMenuBar1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(deskPanel, javax.swing.GroupLayout.Alignment.TRAILING)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(deskPanel)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void subDarAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subDarAltaActionPerformed
                // TODO add your handling code here:
		if(alta == null || !alta.activo){
			alta = new SubAltaProducto();
			deskPanel.add(alta);
			alta.setVisible(true);
		}
        }//GEN-LAST:event_subDarAltaActionPerformed

        private void todosUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todosUsuariosActionPerformed
                
		
		if(usua == null || !usua.activo){
			usua = new SubUsuarios(usuario);
			deskPanel.add(usua);
			usua.setVisible(true);	
		}
        }//GEN-LAST:event_todosUsuariosActionPerformed

        private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
                // TODO add your handling code here:
		if(ventas == null || !ventas.activo){
			ventas = new SubVentasProd();
			deskPanel.add(ventas);
			ventas.setVisible(true);
		}
        }//GEN-LAST:event_jMenuItem1ActionPerformed

        private void subDarBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subDarBajaActionPerformed
                // TODO add your handling code here:
		if(baja == null || !baja.activo){
			baja = new SubBajaProducto();
			deskPanel.add(baja);
			baja.setVisible(true);
		}
        }//GEN-LAST:event_subDarBajaActionPerformed

        private void subModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subModificarActionPerformed
                // TODO add your handling code here:
		if(modifica == null || !modifica.activo){
			modifica = new SubModProducto();
			deskPanel.add(modifica);
			modifica.setVisible(true);
		}
        }//GEN-LAST:event_subModificarActionPerformed

	

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JDesktopPane deskPanel;
        private javax.swing.JMenu jMenu2;
        private javax.swing.JMenuBar jMenuBar1;
        private javax.swing.JMenuItem jMenuItem1;
        private javax.swing.JMenu menuUsuarios;
        private javax.swing.JMenuItem subDarAlta;
        private javax.swing.JMenuItem subDarBaja;
        private javax.swing.JMenuItem subModificar;
        private javax.swing.JMenu subVentas;
        private javax.swing.JMenuItem todosUsuarios;
        // End of variables declaration//GEN-END:variables
}
